### ISSUE TITLE
Transfer ownership of this repo

### ISSUE THREAD

**Issue by alicetragedy** [anjalyes/Team-Hackrgirls-2015#11]
We will be slowly deleting the team repos for the year since they are not needed anymore. 
If you would like to keep this repo @Nidhiya @anjalyes please let me know by commenting here and we can transfer ownership. Otherwise, this repo will be deleted as of next Sunday (December 6th, 2015).

**Comment by alicetragedy** [comment]
@Nidhiya Thanks for the quick response! It is not letting me transfer ownership to your account because you have a repo with that same name (apparently), so I've requested to move it to @anjalyes' account.

**Comment by anjalyes** [comment]
@alicetragedy  I cant accept it..it says it has been expired

**Comment by alicetragedy** [comment]
@anjalyes it has been transferred and is part of your repos right now

**Comment by alicetragedy** [comment]
Should all be fine now. :)
Have a great start of the week – I'll close this issue now :wave:
